### ISSUE TITLE
E2e test for shared mount support for zfspv volumes

### ISSUE THREAD

**Issue by w3aman** [openebs/e2e-tests#436]
- Applications who wants to share a volume can use below storage-class to make their volumes shared by multiple pods
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfspv
parameters:
  shared: "yes"
  fstype: "zfs"
  poolname: "zfspv-pool"
provisioner: zfs.csi.openebs.io
```
